language: java
jdk:
  - oraclejdk7
branches:
  only:
    - master
services:
  - redis-server

env:
- PLAY_VERSION=2.1.0

before_script:
- wget http://download.playframework.org/releases/play-${PLAY_VERSION}.zip
- unzip -q play-${PLAY_VERSION}.zip
